export const defaultConfig = {
  scope: 'default',
  redisPrefix: 'likes',
  cookieName: 'ks_session',
  sessionTTL: 300,
  sessionLimit: 30,
  idPattern: '^[a-zA-Z0-9_\\-]+$',

  rateLimit: {
    enabled: true,
    perIp: {
      enabled: true,
      window: 60000,
      maxRequests: 100,
      blockDuration: 300000,
    },
    perSession: {
      enabled: true,
      cooldown: 300,
      maxPerWindow: 30,
      window: 300,
    },
    perId: {
      enabled: false,
      maxPerDay: 1000,
    },
    global: {
      enabled: true,
      maxPerSecond: 100,
      maxPerMinute: 5000,
      maxPerHour: 100000,
    },
    whitelist: {
      enabled: true,
      ips: [],
      cidrs: [],
    },
  },

  nonce: {
    ttl: 300,
    renewLimit: 3,
    renewWindow: 10,
  },

  security: {
    cors: {
      enabled: true,
      allowOrigin: '*',
      allowMethods: 'GET, POST, OPTIONS',
      allowHeaders: 'Content-Type, X-Nonce',
      exposeHeaders: '',
      maxAge: 86400,
    },
    userAgent: {
      enabled: true,
      minLength: 10,
      blockList: ['curl', 'wget', 'python', 'httpie'],
      allowList: [],
    },
    cookie: {
      secure: true,
      httpOnly: true,
      sameSite: 'Lax',
    },
  },

  request: {
    allowedMethods: ['GET', 'POST'],
    getLimit: 3,
    getWindow: 10,
    bodySizeLimit: 1024,
  },

  performance: {
    redis: {
      pipeline: true,
      luaEnabled: true,
      retryAttempts: 3,
      retryDelay: 100,
      timeout: 5000,
    },
    cache: {
      enabled: false,
      ttl: 60,
      maxItems: 1000,
    },
    async: {
      enabled: true,
      pusherEnabled: true,
      pusherTimeout: 3000,
      queueSize: 100,
    },
    compressionEnabled: true,
    keepAliveEnabled: true,
  },

  pusher: {
    enabled: true,
    appId: process.env.PUSHER_APP_ID || '',
    key: process.env.PUSHER_KEY || '',
    secret: process.env.PUSHER_SECRET || '',
    cluster: process.env.PUSHER_CLUSTER || 'ap3',
    useTLS: true,
    channel: 'shuoshuo-channel',
    event: 'like-event',
  },

  log: {
    enabled: true,
    level: 'info',
    format: 'json',
    colorize: true,
    timestamp: true,
    requestId: true,
    ip: false,
    sessionId: false,
    body: false,
    headers: false,
    redis: false,
    performance: false,
  },

  debug: {
    enabled: false,
    mode: 'production',
    mockRedis: false,
    disableRateLimit: false,
    disableNonce: false,
    disableSession: false,
    disablePusher: false,
    forceError: false,
    throwOnError: false,
    profile: false,
  },

  hooks: {
    onRequestStart: null,
    onRequestEnd: null,
    onRequestError: null,
    onSessionCreate: null,
    onSessionValidate: null,
    onSessionDestroy: null,
    onRateLimitHit: null,
    onIpBlock: null,
    onNonceValidate: null,
    onNonceRenew: null,
    onNonceExpired: null,
    beforeLike: null,
    afterLike: null,
    beforeUnlike: null,
    afterUnlike: null,
    beforeCountUpdate: null,
    afterCountUpdate: null,
    beforeRedisCommand: null,
    afterRedisCommand: null,
    onRedisError: null,
    beforePusherTrigger: null,
    afterPusherTrigger: null,
    onPusherError: null,
    beforeResponse: null,
    afterResponse: null,
    onError: null,
  },
};